source 'https://rubygems.org'

gem "rails", "~> 4.1.0"
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 4.0.3'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
end

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

gem 'minitest'
